console.log('To refresh your session and pick up the new admin role:');
console.log('');
console.log('Option 1 - Sign out and sign back in:');
console.log('1. Go to your app in the browser');
console.log('2. Sign out (if there\'s a sign out button)');
console.log('3. Sign back in');
console.log('');
console.log('Option 2 - Clear browser storage:');
console.log('1. Open browser Developer Tools (F12)');
console.log('2. Go to Application/Storage tab');
console.log('3. Clear all cookies and local storage for localhost:3001');
console.log('4. Refresh the page and sign in again');
console.log('');
console.log('Option 3 - Use incognito/private browsing:');
console.log('1. Open a new incognito/private window');
console.log('2. Go to http://localhost:3001');
console.log('3. Sign in - this will create a fresh session');
console.log('');
console.log('The database shows your role is now "admin", but your JWT token');
console.log('still contains the old "viewer" role. A fresh login will fix this.');